language: node_js
node_js:
  - 10

cache:
  yarn: true
  directories:
  - node_modules

before_install:
- pip install --user codecov
- nvm install v10.14.2
- npm install -g yarn

install:
- yarn install

script:
- yarn build && yarn test

after_success:
- codecov