services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app        # Mount the current directory to /app in the container
      - /app/node_modules   # Prevents overwriting node_modules with the empty directory
    ports:
      - "8080:8080"   # Maps host port 8080 to container port 8080
    environment:
      - NODE_ENV=development
      - SERVER_URL=http://localhost:8000
      - EXTENSION_ROOT_URL=http://localhost:8000/static
      - IS_DEMO_ENVIRONMENT=true
      - IMPORT_BADGE_ALLOWED=true
      - PORT=8080
      - HOSTNAME=localhost
